# Generated by Django 4.0.4 on 2022-06-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(max_length=2000),
        ),
    ]
