# Generated by Django 4.0.4 on 2022-06-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='is_paid',
            new_name='is_signed',
        ),
    ]
