# Generated by Django 4.0.4 on 2022-05-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'managment'), (2, 'support'), (3, 'sales')], default=1, verbose_name='team'),
        ),
    ]
