# Generated by Django 4.0.4 on 2022-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'management'), (2, 'support'), (3, 'sales')], null=True, verbose_name='role'),
        ),
    ]
